import Head from 'next/head';
import styles from '../styles/Home.module.css'
import Image from 'next/image'
import React from 'react';
import ReactDOM from 'react-dom';
import  { useEffect, useState } from 'react';
import axios from 'axios';
import Router from 'next/router'

export default function Home() {

  const[loginDetails, setloginDetails] = React.useState([]);
  const[username, setUsername]=useState([]);
  const[password, setPassword]=useState([]);
  const handleChange =(event)=>{
    this.setState({value:event.target.value});
  }


  useEffect(()=>{
    // fetch(
    //   "http://localhost:8080/login",{
    //     method:'POST', body:{
    //       "uname": "user1",
    //       "password": "123"
    //     }
  
    //   }
    // ).then(res=> res.json()).then(result=>console.log(result))

    
  // axios.post("http://localhost:8080/login",{
  // "username":"user1",
  // "password": "123"
  // })
  // .then (function (response){
  //   console.log(response.data.message);
  //   if(response.data.message=='Authorized'){
  //     window.location.href="/homepage"
  //   }
  // })
  // .catch(function(error){
  //   console.log(error);
  // });
  
    
   })
  let login=(e) =>{
    e.preventDefault();
    axios.post("http://localhost:8080/login", {
      "username":username,
      "password": password
    })
    .then (function (response){
      console.log(response.data.message);
      if(response.data.message=='Login Sucessful'){
       // window.location.href="/profile"
       Router.push('/dailycatch')

      }
     
    })
    .catch(function(error){
      console.log(error);
    });
  };


  return (
    <div className={styles.container}>
      <Head>
        <title>Oceanus Login</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
      <section>
                <div className={styles.imgbox}> 
                <Image  src= "/image 15.png"alt= "Ocenaus image" height={621} width={700} />
                </div>
            </section>
            <div className={styles.contentbx}>
                
                        <form onSubmit={login}>
                        <Image  className={styles.vector} height="120px" width="100px" src="/frame.jpg" alt="vector image"/>
                        <h2 className={styles.h2}>LOGIN</h2>
                        <h3 className={styles.h3}>Welcome to Oceanus </h3>
                        <div className={styles.inputbx}>
                            <input className={styles.input} type="text" id="userid" value={username} placeholder="User name" onChange={e =>setUsername(e.target.value)}/>
                        </div>
                        <div className={styles.inputbx}>               
                            <input type="password" placeholder="Password" id="password" name="" className={styles.input} value={password} onChange={e =>setPassword(e.target.value)}/>
                        </div>
                        <div className={styles.remember}>
                            <label><input type="checkbox" name=""/> Remember me</label>
                            <span className={styles.forgot}><a  href="">Forgot Password </a></span>
                        </div>

                       <div className={styles.inputbx}>
                        <input className={styles.button} type="submit" value="LOGIN"  />  
                       
                       </div>

                    <div id="result" className={styles.display}>

                    </div>
                    
                </form>
                </div>
                </main>
                </div>

  )
}
